name: Compile GoModCheater
on:
  push:
    branches: 
      - master

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  my-job:
    name: Build GoModCheater 🚀
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      
    - name: Build
      run: export GOOS=windows; export GOARCH=amd64; export GO111MODULE=off; go build -ldflags="-s -w" -o artifacts/GoModCheater.exe
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: GoModCheater.exe
        path: ./artifacts
